name: easy_mrz
description: Fast MRZ (Machine Readable Zone) scanning for identity documents on iOS and Android.
version: 1.0.0+1
homepage: https://github.com/kingace2056/easy_mrz
repository: https://github.com/kingace2056/easy_mrz
issue_tracker: https://github.com/kingace2056/easy_mrz/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  mrz_parser: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.mlabs.easy_mrz
        pluginClass: FlutterMrzScannerPlugin
      ios:
        pluginClass: FlutterMrzScannerPlugin
